### ISSUE TITLE
Clarifying auth0-simulator README

### ISSUE THREAD

**Issue by minkimcello** [thefrontside/simulacrum#106]
Some thoughts I had while going through the README:

- It might be obvious to everyone else but it could be worth mentioning that the quick start in the readme of `auth0-simulator` assumes you have your own app that uses auth0.
  - And for examples that comes with an app, point to the examples in the [examples directory](https://github.com/thefrontside/simulacrum/tree/v0/examples).

> [This mutation creates your first simulation, and runs it in memory.](https://github.com/thefrontside/simulacrum/blob/v0/packages/auth0/README.md#graphql)

In memory?

> [`import { auth0 } from ".";`](https://github.com/thefrontside/simulacrum/blob/v0/packages/auth0/README.md#code)

Shouldn't this be importing from `@simulacrum/auth0-simulator`?

- Should we explain the difference between the simulation service (port 4000) and auth0 service (port 4400) to say that your app should configure auth0 to direct to port 4400 and not 4000?

- Would appreciate some clarity around the first and second argument of `client.createSimulation("auth0", ...config)` and `client given(simulation, "person")` respectively
  - Is `"auth0"` of `createSimulation()` a hard-coded value? Or is it just a label?
    - Same question for "person"

**Comment by jbolda** [comment]
> It might be obvious to everyone else but it could be worth mentioning that the quick start in the readme of auth0-simulator assumes you have your own app that uses auth0.

That makes sense. We might want to add a heading / note that says for using it with your existing app. "If you want to try it out, see the examples."

> In memory?

As in, the state of the server is not saved to disk. When you shut down and start the server back up again, you will need to run these again to get back to the same state you had when you shut it down.

> Shouldn't this be importing from @simulacrum/auth0-simulator?

Yea, we should use the package name there.

> Should we explain the difference between the simulation service (port 4000) and auth0 service (port 4400) to say that your app should configure auth0 to direct to port 4400 and not 4000?

I imagine we put that explanation in the main simulacrum docs as this kind of falls under the architecture. What do you think @cowboyd ?

> Would appreciate some clarity around the first and second argument [...]

Yea, these are effectively ENUMs, effectively hard coded, but the options will expand as we add more simulators. I wonder if we can list the current options or something in the main simulacrum docs and use that as a way to point to each simulator package readme?
