### ISSUE TITLE
Incorrect path displayed for configuring the certificate

### ISSUE THREAD

**Issue by minkimcello** [thefrontside/simulacrum#107]
Simulacrum expects the `.simulacrum/certs` to be located in `~/.simulacrum/certs` but in the console output for when you run a graphql query without authentication, it shows:
```
brew install mkcert
brew install nss  # for firefox

mkdir -p /Users/MYMACBOOK/.simulacrum/certs
cd /Users/MYMACBOOK/.simulacrum/certs
```

It would be nice to let users know where simulacrum looks for these certs by default and also allow users to be able to configure their own path if they want to (if it's not a feature that's already available).

**Comment by dagda1** [comment]
@minkimcello that is surprising that is wrong.  

The error message is created using the `paths` that it checks if the file exists

```ts
export const mkcertText = `
In order to run an https service from localhost you need locally-trusted development certificates.

mkcert (https://github.com/FiloSottile/mkcert) makes this pretty easy:

brew install mkcert
brew install nss  # for firefox

mkdir -p ${paths.certificatesDir}
cd ${paths.certificatesDir}

mkcert -install   # Created a new local CA at the location returned from mkcert -CAROOT
mkcert localhost  # Using the local CA at CAROOT, create a new certificate valid for the following names
      `;
```

And `paths.certificatesDir` is what is checked against when the exception is thrown:

```ts
      if([paths.ssl.keyFile, paths.ssl.pemFile].some(f => !fs.existsSync(f))){
        console.warn(mkcertText);

        throw new NoSSLError('no self signed certificate.');
      }
```

**Comment by minkimcello** [comment]
<img width="756" alt="Screen Shot 2021-07-30 at 9 22 54 AM" src="https://user-images.githubusercontent.com/29791650/127659715-f571bcff-98a2-4fd2-9e84-38a0f81cd016.png">

I think the reason why it's confusing is because there's...
```
/Users/minkimcello/
/Users/minkimcello/Users/minkimcello/
```
So even though I should've put the certs in `~/.simulacrum`, I ended up putting it in `~/Users/minkimcello/.simulacrum` because of the console output.

**Comment by dagda1** [comment]
who added the extra tilde that is not in the console output? :).

**Comment by minkimcello** [comment]
Unless they're running `yarn start --cwd /projects/wherever/simulacrum/packages/auth0`,  I think we can assume `mkdir /Users/minkimcello/.simulacrum/certs` will create a directory INSIDE the auth0 package. Is that what we want?

**Comment by dagda1** [comment]
I was expecting the path to be copied and pasted

`/Users/minkimcello/.simulacrum/certs` is an absolute path unless I am missing something.  It won't create it in `auth0`.

**Comment by dagda1** [comment]
<img width="1229" alt="m" src="https://user-images.githubusercontent.com/118328/127661190-19636b8d-46f7-425c-a0c3-3b4b2dac0b45.png">

**Comment by minkimcello** [comment]
Oh i didn't know the first `/` made the path absolute.

**Comment by minkimcello** [comment]
Nevermind then
