### ISSUE TITLE
Caught error in run loop `task 13` after upgrading to Effection 2.0.0-beta.21

### ISSUE THREAD

**Issue by taras** [thefrontside/simulacrum#134]
@chuckcarpenter [ reported this issue in Discord](https://discord.com/channels/700803887132704931/740223385019351051/894701178259116052
) and @wKich was able to reproduce it.

Running Simulacrum triggers this error after upgrading to `effection@2.0.0-beta.21`. Rolling back to `effection@2.0.0-beta.17` seems to restore functionality. I looked at our tests and it looks like we're not starting Simulacrum there. We should at least start the server and start the echo simulator.

**Comment by cowboyd** [comment]
> I looked at our tests and it looks like we're not starting Simulacrum there. We should at least start the server and start the echo simulator.

We are definitely [starting the simulacrum server in the tests](https://github.com/thefrontside/simulacrum/blob/v0/packages/server/test/server.test.ts#L35), but this appears not to be sufficient enough in that this should have definitely been caught.

@wKich Can you post a reproduction of this?

**Comment by wKich** [comment]
@cowboyd you can merge v0 to #114 and try to run a simulation server in the cypress integration tests

**Comment by wKich** [comment]
@cowboyd I think it is also fixed. We prepared for the demo and you got the same error

**Comment by cowboyd** [comment]
Yeah, we released 2.0 and got a confirmation that the fix worked.
