### ISSUE TITLE
Auth0 Simulation Demo

### ISSUE THREAD

**Issue by taras** [thefrontside/simulacrum#53]
We want to showcase how Auth0 simulation with Simulacrum can ease testing with Auth0 and improve the developer experience. 

To do  this, we want to prepare a demo that shows the following

1. react-auth0 can use our Auth0 simulator by changing the domain to point to our simulator without modifying react-auth0 library
2. we can use a helper to authenticate the app in an end-to-end test suite (preferably with Cypress)
3. we can control the state of Auth0 simulator from tests - we can create multiple user accounts

We have a few stretch goals that we want to introduce if we have the time
1. Show that we can control rules in auth0 simulator via the simulation API
2. Show how auth0 simulator can work with a GraphQL API where GraphQL has to verify a token provided by the frontend

**Comment by elrickvm** [comment]
Progress update as of May 19...
* Volta upgraded
* Simulacrum brought into repo
* Simulacrum builds in repo
* Auth0 initial simulator can build in repo
* Initial test case written to ensure simulation will spawn
* Auth0 Simulator setup in template form to start bringing the code from the spike and other code base

Next Phase:
* Auth0 working code from spike and other code base will be start be intergrated in Auth0 Simulator package in simulacrum and the Demo app.
