### ISSUE TITLE
auth0 simulator missing image on login page

### ISSUE THREAD

**Issue by jbolda** [thefrontside/simulacrum#95]
We have an image referenced in the [login view that is missing](https://github.com/thefrontside/simulacrum/blob/v0/packages/auth0/src/views/login.ts#L36).

**Comment by dagda1** [comment]
it is fine when viewed in any other route apart from when `/login/` is viewed directly

**Comment by dagda1** [comment]
and the /login route is purely for debug

**Comment by jbolda** [comment]
Assuming I am not misunderstanding, the example using `auth0-react` seems to redirect to it.

**Comment by dagda1** [comment]
auth0-react redirects to `/usernamepassword/login` and not `/login`.

Can you point me to an actual example that is broken and not one where you just hit `/login` directly?

**Comment by jbolda** [comment]
I configured both examples according to their docs.


https://user-images.githubusercontent.com/2019387/126664522-8793f1be-e33e-4510-9e44-f100931b2d90.mp4

**Comment by dagda1** [comment]
ok, where is the code and i can take a look?

**Comment by jbolda** [comment]
If you follow the readme in `./examples/nextjs-with-auth0-react` in #97, you should be able to reproduce it.

**Comment by dagda1** [comment]
@jbolda oh yes, I know what this is now.  

Nice one, I'm going to create a separate PR.  This is totally a bug

**Comment by dagda1** [comment]
@jbolda #98 cures this great evil

**Comment by jbolda** [comment]
Closing per #98.
