### ISSUE TITLE
Halted effects are leaked

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/simulacrum#99]
When an effect is discarded because it's underlying data is removed, we halt the effect, but we don't actually remove it from the set of effects (which really ought to be comprised of active effects.)

This means that each effect mapping will grow in memory indefinitely.

https://github.com/thefrontside/simulacrum/blob/v0/packages/server/src/effect.ts#L33

Instead, we should remove each effect after it is halted. Note that I'm not sure that this can be tested.

**Comment by wKich** [comment]
@cowboyd I think it was fixed. We remove effect when we're halting it

**Comment by cowboyd** [comment]
I think you're right!
